version: "2"

services:
  teampass-db:
    restart: always
    image: mysql:5.6 
    ports:
      - "172.16.50.18:3306:3306"
    labels:
      SERVICE_OWNER: infra
      SERVICE_TYPE: passmanager
      SERVICE_LABEL: db
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
      - "/var/dockershared/passmgr/db:/var/lib/mysql:rw"
    environment:
      MYSQL_ROOT_PASSWORD: 4dm1nSd1g1tS 
      MYSQL_DATABASE: teampass
      MYSQL_PASSWORD: t34mP4sSw0rD 
      MYSQL_USER: teampassApp 
    networks:
      - passmgr

  teampass-app:
    restart: always
    build:
       context: .
       dockerfile: Dockerfile.web
    ports:
      - "172.16.50.18:80:80"
      - "172.16.50.18:443:443"
    labels:
      SERVICE_OWNER: infra
      SERVICE_TYPE: passmanager
      SERVICE_LABEL: app
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "1"
    volumes:
        - "/certificates:/var/dockershared/passmgr/certificates:ro"
    links:
      - teampass-db:db
    depends_on:
      - teampass-db
    networks:
      - passmgr

networks:
  passmgr: