FROM alpine

ENV TP_VER 2.1.27.30
ENV TZ Europe/Madrid

WORKDIR /var/www/localhost/htdocs

RUN apk update \
    && apk add tzdata curl apache2 apache2-ssl php5 php5-apache2 php5-mcrypt php5-openssl php5-bcmath php5-iconv php5-xml php5-gd php5-curl php5-json php5-mysqli php5-ldap \
    && curl -sL https://github.com/nilsteampassnet/TeamPass/archive/${TP_VER}.tar.gz -o teampass.tar.gz \
    && tar -xzf teampass.tar.gz \
    && mv TeamPass-${TP_VER}/* . \
    && rm -rf TeamPass-${TP_VER} \
    && rm teampass.tar.gz 

RUN mkdir -p /run/apache2 

RUN sed -i 's/^\(.*DirectoryIndex.*\)$/#\1/g' /etc/apache2/httpd.conf \
    && sed -i 's/^\(max_execution_time = \).*$/\160/g' /etc/php5/php.ini

ADD conf/ /etc/apache2/conf.d/
ADD ssl/certificates/ /certificates

RUN ln -s /dev/stdout /var/log/apache2/access.log \
    && ln -s /dev/stderr /var/log/apache2/error.log \
    && ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime \
    && chown -R apache.apache /var/www/localhost/htdocs 

ENTRYPOINT ["httpd","-D","FOREGROUND"]